name: application_laboratorio
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.17
  logger: ^2.5.0
  provider: ^6.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0


flutter:

  uses-material-design: true

  assets:
    - assets/icons/mobile.svg
    - assets/icons/check.svg

  fonts:
    - family: Pokemon
      fonts:
        - asset: assets/fonts/Pokemon Hollow.ttf
        - asset: assets/fonts/Pokemon Solid.ttf
    - family: Comic
      fonts:
        - asset: assets/fonts/Hey Comic.ttf

 
